version: '3'

services:
  vehicle-api:
    container_name: "vehicle-api"
    links:
      - vehicle-db
    depends_on:
      - vehicle-db
    ports:
      - '8080:8080'
    build: "./deployment"
    volumes:
    - ./:/app
    environment:
      SERVER_PORT: "8080"
      POSTGRES_HOST: "vehicle-db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres-user"
      POSTGRES_PASSWORD: "postgres-pass"
      POSTGRES_DB: "postgres-db"
  vehicle-db:
    container_name: "vehicle-db"
    image: postgres:10.6
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: 1
      POSTGRES_USER: "postgres-user"
      POSTGRES_PASSWORD: "postgres-pass"
      POSTGRES_DB: "postgres-db"
