// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.3
// source: protos/vehicleapi.proto

package vehicleapi_proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VehicleCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Make  string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Vin   string `protobuf:"bytes,4,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *VehicleCreateRequest) Reset() {
	*x = VehicleCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCreateRequest) ProtoMessage() {}

func (x *VehicleCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCreateRequest.ProtoReflect.Descriptor instead.
func (*VehicleCreateRequest) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleCreateRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleCreateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleCreateRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type VehicleCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make  string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Vin   string `protobuf:"bytes,4,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *VehicleCreateResponse) Reset() {
	*x = VehicleCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCreateResponse) ProtoMessage() {}

func (x *VehicleCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCreateResponse.ProtoReflect.Descriptor instead.
func (*VehicleCreateResponse) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleCreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VehicleCreateResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleCreateResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleCreateResponse) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type VehicleReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VehicleReadRequest) Reset() {
	*x = VehicleReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleReadRequest) ProtoMessage() {}

func (x *VehicleReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleReadRequest.ProtoReflect.Descriptor instead.
func (*VehicleReadRequest) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleReadRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VehicleReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make  string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Vin   string `protobuf:"bytes,4,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *VehicleReadResponse) Reset() {
	*x = VehicleReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleReadResponse) ProtoMessage() {}

func (x *VehicleReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleReadResponse.ProtoReflect.Descriptor instead.
func (*VehicleReadResponse) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{3}
}

func (x *VehicleReadResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VehicleReadResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleReadResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleReadResponse) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type VehicleSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Make  string `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *VehicleSearchRequest) Reset() {
	*x = VehicleSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleSearchRequest) ProtoMessage() {}

func (x *VehicleSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleSearchRequest.ProtoReflect.Descriptor instead.
func (*VehicleSearchRequest) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{4}
}

func (x *VehicleSearchRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleSearchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type VehicleSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make  string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Vin   string `protobuf:"bytes,4,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *VehicleSearchResponse) Reset() {
	*x = VehicleSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleSearchResponse) ProtoMessage() {}

func (x *VehicleSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleSearchResponse.ProtoReflect.Descriptor instead.
func (*VehicleSearchResponse) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{5}
}

func (x *VehicleSearchResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VehicleSearchResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleSearchResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleSearchResponse) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type VehicleUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make  string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Vin   string `protobuf:"bytes,4,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *VehicleUpdateRequest) Reset() {
	*x = VehicleUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleUpdateRequest) ProtoMessage() {}

func (x *VehicleUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleUpdateRequest.ProtoReflect.Descriptor instead.
func (*VehicleUpdateRequest) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{6}
}

func (x *VehicleUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VehicleUpdateRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleUpdateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleUpdateRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type VehicleUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountUpdated int64 `protobuf:"varint,1,opt,name=countUpdated,proto3" json:"countUpdated,omitempty"`
}

func (x *VehicleUpdateResponse) Reset() {
	*x = VehicleUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleUpdateResponse) ProtoMessage() {}

func (x *VehicleUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleUpdateResponse.ProtoReflect.Descriptor instead.
func (*VehicleUpdateResponse) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{7}
}

func (x *VehicleUpdateResponse) GetCountUpdated() int64 {
	if x != nil {
		return x.CountUpdated
	}
	return 0
}

type VehicleDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VehicleDeleteRequest) Reset() {
	*x = VehicleDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleDeleteRequest) ProtoMessage() {}

func (x *VehicleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleDeleteRequest.ProtoReflect.Descriptor instead.
func (*VehicleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{8}
}

func (x *VehicleDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VehicleDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountDeleted int64 `protobuf:"varint,1,opt,name=countDeleted,proto3" json:"countDeleted,omitempty"`
}

func (x *VehicleDeleteResponse) Reset() {
	*x = VehicleDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vehicleapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleDeleteResponse) ProtoMessage() {}

func (x *VehicleDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vehicleapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleDeleteResponse.ProtoReflect.Descriptor instead.
func (*VehicleDeleteResponse) Descriptor() ([]byte, []int) {
	return file_protos_vehicleapi_proto_rawDescGZIP(), []int{9}
}

func (x *VehicleDeleteResponse) GetCountDeleted() int64 {
	if x != nil {
		return x.CountDeleted
	}
	return 0
}

var File_protos_vehicleapi_proto protoreflect.FileDescriptor

var file_protos_vehicleapi_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x14, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x69, 0x6e, 0x22, 0x63, 0x0a,
	0x15, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76,
	0x69, 0x6e, 0x22, 0x24, 0x0a, 0x12, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x13, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x69, 0x6e, 0x22, 0x40, 0x0a, 0x14, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x63, 0x0a,
	0x15, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76,
	0x69, 0x6e, 0x22, 0x62, 0x0a, 0x14, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61,
	0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x76, 0x69, 0x6e, 0x22, 0x3b, 0x0a, 0x15, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x15, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x32, 0xd0, 0x02, 0x0a, 0x08, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0d, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x12, 0x13, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x15, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x0d, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x3b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x61, 0x70, 0x69,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_vehicleapi_proto_rawDescOnce sync.Once
	file_protos_vehicleapi_proto_rawDescData = file_protos_vehicleapi_proto_rawDesc
)

func file_protos_vehicleapi_proto_rawDescGZIP() []byte {
	file_protos_vehicleapi_proto_rawDescOnce.Do(func() {
		file_protos_vehicleapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vehicleapi_proto_rawDescData)
	})
	return file_protos_vehicleapi_proto_rawDescData
}

var file_protos_vehicleapi_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_vehicleapi_proto_goTypes = []interface{}{
	(*VehicleCreateRequest)(nil),  // 0: VehicleCreateRequest
	(*VehicleCreateResponse)(nil), // 1: VehicleCreateResponse
	(*VehicleReadRequest)(nil),    // 2: VehicleReadRequest
	(*VehicleReadResponse)(nil),   // 3: VehicleReadResponse
	(*VehicleSearchRequest)(nil),  // 4: VehicleSearchRequest
	(*VehicleSearchResponse)(nil), // 5: VehicleSearchResponse
	(*VehicleUpdateRequest)(nil),  // 6: VehicleUpdateRequest
	(*VehicleUpdateResponse)(nil), // 7: VehicleUpdateResponse
	(*VehicleDeleteRequest)(nil),  // 8: VehicleDeleteRequest
	(*VehicleDeleteResponse)(nil), // 9: VehicleDeleteResponse
}
var file_protos_vehicleapi_proto_depIdxs = []int32{
	0, // 0: Vehicles.VehicleCreate:input_type -> VehicleCreateRequest
	2, // 1: Vehicles.VehicleRead:input_type -> VehicleReadRequest
	4, // 2: Vehicles.VehicleSearch:input_type -> VehicleSearchRequest
	6, // 3: Vehicles.VehicleUpdate:input_type -> VehicleUpdateRequest
	8, // 4: Vehicles.VehicleDelete:input_type -> VehicleDeleteRequest
	1, // 5: Vehicles.VehicleCreate:output_type -> VehicleCreateResponse
	3, // 6: Vehicles.VehicleRead:output_type -> VehicleReadResponse
	5, // 7: Vehicles.VehicleSearch:output_type -> VehicleSearchResponse
	7, // 8: Vehicles.VehicleUpdate:output_type -> VehicleUpdateResponse
	9, // 9: Vehicles.VehicleDelete:output_type -> VehicleDeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_vehicleapi_proto_init() }
func file_protos_vehicleapi_proto_init() {
	if File_protos_vehicleapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vehicleapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vehicleapi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vehicleapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vehicleapi_proto_goTypes,
		DependencyIndexes: file_protos_vehicleapi_proto_depIdxs,
		MessageInfos:      file_protos_vehicleapi_proto_msgTypes,
	}.Build()
	File_protos_vehicleapi_proto = out.File
	file_protos_vehicleapi_proto_rawDesc = nil
	file_protos_vehicleapi_proto_goTypes = nil
	file_protos_vehicleapi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VehiclesClient is the client API for Vehicles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VehiclesClient interface {
	VehicleCreate(ctx context.Context, in *VehicleCreateRequest, opts ...grpc.CallOption) (*VehicleCreateResponse, error)
	VehicleRead(ctx context.Context, in *VehicleReadRequest, opts ...grpc.CallOption) (*VehicleReadResponse, error)
	VehicleSearch(ctx context.Context, in *VehicleSearchRequest, opts ...grpc.CallOption) (Vehicles_VehicleSearchClient, error)
	VehicleUpdate(ctx context.Context, in *VehicleUpdateRequest, opts ...grpc.CallOption) (*VehicleUpdateResponse, error)
	VehicleDelete(ctx context.Context, in *VehicleDeleteRequest, opts ...grpc.CallOption) (*VehicleDeleteResponse, error)
}

type vehiclesClient struct {
	cc grpc.ClientConnInterface
}

func NewVehiclesClient(cc grpc.ClientConnInterface) VehiclesClient {
	return &vehiclesClient{cc}
}

func (c *vehiclesClient) VehicleCreate(ctx context.Context, in *VehicleCreateRequest, opts ...grpc.CallOption) (*VehicleCreateResponse, error) {
	out := new(VehicleCreateResponse)
	err := c.cc.Invoke(ctx, "/Vehicles/VehicleCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiclesClient) VehicleRead(ctx context.Context, in *VehicleReadRequest, opts ...grpc.CallOption) (*VehicleReadResponse, error) {
	out := new(VehicleReadResponse)
	err := c.cc.Invoke(ctx, "/Vehicles/VehicleRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiclesClient) VehicleSearch(ctx context.Context, in *VehicleSearchRequest, opts ...grpc.CallOption) (Vehicles_VehicleSearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Vehicles_serviceDesc.Streams[0], "/Vehicles/VehicleSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &vehiclesVehicleSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Vehicles_VehicleSearchClient interface {
	Recv() (*VehicleSearchResponse, error)
	grpc.ClientStream
}

type vehiclesVehicleSearchClient struct {
	grpc.ClientStream
}

func (x *vehiclesVehicleSearchClient) Recv() (*VehicleSearchResponse, error) {
	m := new(VehicleSearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vehiclesClient) VehicleUpdate(ctx context.Context, in *VehicleUpdateRequest, opts ...grpc.CallOption) (*VehicleUpdateResponse, error) {
	out := new(VehicleUpdateResponse)
	err := c.cc.Invoke(ctx, "/Vehicles/VehicleUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiclesClient) VehicleDelete(ctx context.Context, in *VehicleDeleteRequest, opts ...grpc.CallOption) (*VehicleDeleteResponse, error) {
	out := new(VehicleDeleteResponse)
	err := c.cc.Invoke(ctx, "/Vehicles/VehicleDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VehiclesServer is the server API for Vehicles service.
type VehiclesServer interface {
	VehicleCreate(context.Context, *VehicleCreateRequest) (*VehicleCreateResponse, error)
	VehicleRead(context.Context, *VehicleReadRequest) (*VehicleReadResponse, error)
	VehicleSearch(*VehicleSearchRequest, Vehicles_VehicleSearchServer) error
	VehicleUpdate(context.Context, *VehicleUpdateRequest) (*VehicleUpdateResponse, error)
	VehicleDelete(context.Context, *VehicleDeleteRequest) (*VehicleDeleteResponse, error)
}

// UnimplementedVehiclesServer can be embedded to have forward compatible implementations.
type UnimplementedVehiclesServer struct {
}

func (*UnimplementedVehiclesServer) VehicleCreate(context.Context, *VehicleCreateRequest) (*VehicleCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VehicleCreate not implemented")
}
func (*UnimplementedVehiclesServer) VehicleRead(context.Context, *VehicleReadRequest) (*VehicleReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VehicleRead not implemented")
}
func (*UnimplementedVehiclesServer) VehicleSearch(*VehicleSearchRequest, Vehicles_VehicleSearchServer) error {
	return status.Errorf(codes.Unimplemented, "method VehicleSearch not implemented")
}
func (*UnimplementedVehiclesServer) VehicleUpdate(context.Context, *VehicleUpdateRequest) (*VehicleUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VehicleUpdate not implemented")
}
func (*UnimplementedVehiclesServer) VehicleDelete(context.Context, *VehicleDeleteRequest) (*VehicleDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VehicleDelete not implemented")
}

func RegisterVehiclesServer(s *grpc.Server, srv VehiclesServer) {
	s.RegisterService(&_Vehicles_serviceDesc, srv)
}

func _Vehicles_VehicleCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).VehicleCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Vehicles/VehicleCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).VehicleCreate(ctx, req.(*VehicleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicles_VehicleRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).VehicleRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Vehicles/VehicleRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).VehicleRead(ctx, req.(*VehicleReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicles_VehicleSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VehicleSearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VehiclesServer).VehicleSearch(m, &vehiclesVehicleSearchServer{stream})
}

type Vehicles_VehicleSearchServer interface {
	Send(*VehicleSearchResponse) error
	grpc.ServerStream
}

type vehiclesVehicleSearchServer struct {
	grpc.ServerStream
}

func (x *vehiclesVehicleSearchServer) Send(m *VehicleSearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Vehicles_VehicleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).VehicleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Vehicles/VehicleUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).VehicleUpdate(ctx, req.(*VehicleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicles_VehicleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiclesServer).VehicleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Vehicles/VehicleDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiclesServer).VehicleDelete(ctx, req.(*VehicleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vehicles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Vehicles",
	HandlerType: (*VehiclesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VehicleCreate",
			Handler:    _Vehicles_VehicleCreate_Handler,
		},
		{
			MethodName: "VehicleRead",
			Handler:    _Vehicles_VehicleRead_Handler,
		},
		{
			MethodName: "VehicleUpdate",
			Handler:    _Vehicles_VehicleUpdate_Handler,
		},
		{
			MethodName: "VehicleDelete",
			Handler:    _Vehicles_VehicleDelete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VehicleSearch",
			Handler:       _Vehicles_VehicleSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/vehicleapi.proto",
}
